<?php $title = 'Projects, services & courses'; ?>
<div class="pagehead"><div><h1>Projects, services &amp; courses</h1><p>Hide or remove listings that don’t belong on the platform.</p></div></div>
<h3><?= icon('rocket', 18) ?> Projects</h3>
<div class="table-wrap mb"><table class="t"><thead><tr><th>Title</th><th>Owner</th><th>Status</th><th>Visibility</th><th></th></tr></thead><tbody>
<?php foreach ($projects as $r): ?><tr><td><a href="<?= e(url('projects/' . $r['id'])) ?>"><b><?= e(excerpt($r['title'], 60)) ?></b></a></td><td><?= e($r['full_name']) ?></td><td><span class="status-pill st-<?= e($r['status']) ?>"><?= e(str_replace('_', ' ', $r['status'])) ?></span></td><td><span class="status-pill st-<?= $r['hidden'] ? 'hidden' : 'visible' ?>"><?= $r['hidden'] ? 'hidden' : 'visible' ?></span></td>
<td style="text-align:right"><form method="post" action="<?= e(url('admin/moderate')) ?>" class="row" style="justify-content:flex-end;gap:6px"><?= csrf_field() ?><input type="hidden" name="type" value="project"><input type="hidden" name="id" value="<?= (int) $r['id'] ?>"><button class="btn btn-sm" name="action" value="<?= $r['hidden'] ? 'restore' : 'hide' ?>"><?= $r['hidden'] ? 'Restore' : 'Hide' ?></button><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete this project?')"><?= icon('trash', 13) ?></button></form></td></tr><?php endforeach ?>
<?php if (!$projects): ?><tr><td colspan="5" class="tc muted" style="padding:24px">No projects.</td></tr><?php endif ?></tbody></table></div>
<h3><?= icon('store', 18) ?> Services</h3>
<div class="table-wrap mb"><table class="t"><thead><tr><th>Title</th><th>Provider</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($services as $r): ?><tr><td><a href="<?= e(url('marketplace/' . $r['id'])) ?>"><b><?= e(excerpt($r['title'], 60)) ?></b></a></td><td><?= e($r['full_name']) ?></td><td><?= $r['price'] ? 'AED ' . (int) $r['price'] : 'Free' ?></td><td><span class="status-pill st-<?= e($r['status']) ?>"><?= e($r['status']) ?></span></td>
<td style="text-align:right"><form method="post" action="<?= e(url('admin/moderate')) ?>" class="row" style="justify-content:flex-end;gap:6px"><?= csrf_field() ?><input type="hidden" name="type" value="service"><input type="hidden" name="id" value="<?= (int) $r['id'] ?>"><button class="btn btn-sm" name="action" value="<?= $r['status'] === 'hidden' ? 'restore' : 'hide' ?>"><?= $r['status'] === 'hidden' ? 'Restore' : 'Hide' ?></button><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete this service?')"><?= icon('trash', 13) ?></button></form></td></tr><?php endforeach ?>
<?php if (!$services): ?><tr><td colspan="5" class="tc muted" style="padding:24px">No services.</td></tr><?php endif ?></tbody></table></div>
<h3><?= icon('book', 18) ?> Courses</h3>
<div class="table-wrap"><table class="t"><thead><tr><th>Title</th><th>Teacher</th><th>Students</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach ($courses as $r): ?><tr><td><a href="<?= e(url('learn/' . $r['id'])) ?>"><b><?= e(excerpt($r['title'], 60)) ?></b></a></td><td><?= e($r['full_name']) ?></td><td><?= (int) $r['students'] ?></td><td><span class="status-pill st-<?= e($r['status']) ?>"><?= e($r['status']) ?></span></td>
<td style="text-align:right"><form method="post" action="<?= e(url('admin/courses/' . $r['id'] . '/toggle')) ?>"><?= csrf_field() ?><button class="btn btn-sm"><?= $r['status'] === 'published' ? 'Unpublish' : 'Publish' ?></button></form></td></tr><?php endforeach ?>
<?php if (!$courses): ?><tr><td colspan="5" class="tc muted" style="padding:24px">No courses.</td></tr><?php endif ?></tbody></table></div>
