<?php $title = 'Moderation'; ?>
<div class="pagehead"><div><h1>Moderation</h1><p>Review reports, hide or remove content that breaks the community rules.</p></div></div>
<h3>Reports</h3>
<div class="table-wrap mb"><table class="t"><thead><tr><th>Status</th><th>Reported content</th><th>Reason</th><th>By</th><th style="text-align:right">Action</th></tr></thead><tbody>
<?php foreach ($reports as $r): $pv = $r['preview']; ?>
<tr><td><span class="status-pill st-<?= $r['status'] === 'open' ? 'pending' : 'closed' ?>"><?= e($r['status']) ?></span></td>
<td style="max-width:360px"><span class="chip sm"><?= e($r['target_type']) ?> #<?= (int) $r['target_id'] ?></span> <?php if ($pv): ?><b class="small"><?= e(excerpt($pv['text'], 80)) ?></b><div class="xs muted">by <?= e($pv['author']) ?> · <?= e($pv['status']) ?></div><?php else: ?><span class="muted small">(deleted)</span><?php endif ?></td>
<td class="small"><?= e($r['reason']) ?></td><td class="small"><?= e($r['reporter']) ?><div class="xs muted"><?= e(time_ago($r['created_at'])) ?></div></td>
<td style="text-align:right"><?php if ($r['status'] === 'open'): ?><form method="post" action="<?= e(url('admin/moderate')) ?>" class="row" style="justify-content:flex-end;gap:6px;flex-wrap:wrap"><?= csrf_field() ?><input type="hidden" name="type" value="<?= e($r['target_type']) ?>"><input type="hidden" name="id" value="<?= (int) $r['target_id'] ?>"><input type="hidden" name="report_id" value="<?= (int) $r['id'] ?>">
  <?php if ($pv): ?><button class="btn btn-sm" name="action" value="hide">Hide</button><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete this content permanently?')">Delete</button><?php endif ?><button class="btn btn-sm btn-ghost" name="action" value="dismiss">Dismiss</button></form><?php endif ?></td></tr>
<?php endforeach ?><?php if (!$reports): ?><tr><td colspan="5" class="tc muted" style="padding:30px">No reports yet. 🎉</td></tr><?php endif ?></tbody></table></div>
<h3>Recent posts</h3>
<div class="table-wrap"><table class="t"><thead><tr><th>Post</th><th>Author</th><th>Type</th><th>Status</th><th>When</th><th style="text-align:right"></th></tr></thead><tbody>
<?php foreach ($recent as $p): ?><tr><td><a href="<?= e(url('post/' . $p['id'])) ?>"><b><?= e(excerpt($p['title'], 60)) ?></b></a> <?= $p['pinned'] ? '📌' : '' ?></td><td><?= e($p['full_name']) ?></td><td><span class="chip sm tchip tone-<?= e(post_type($p['type'])['tone']) ?>"><?= e(post_type($p['type'])['label']) ?></span></td><td><span class="status-pill st-<?= e($p['status']) ?>"><?= e($p['status']) ?></span></td><td class="muted small"><?= e(time_ago($p['created_at'])) ?></td>
<td style="text-align:right"><form method="post" action="<?= e(url('admin/moderate')) ?>" class="row" style="justify-content:flex-end;gap:6px"><?= csrf_field() ?><input type="hidden" name="type" value="post"><input type="hidden" name="id" value="<?= (int) $p['id'] ?>"><?php if ($p['status'] === 'visible'): ?><button class="btn btn-sm" name="action" value="hide">Hide</button><?php else: ?><button class="btn btn-sm btn-primary" name="action" value="restore">Restore</button><?php endif ?><button class="btn btn-sm btn-danger" name="action" value="delete" onclick="return confirm('Delete permanently?')"><?= icon('trash', 13) ?></button></form></td></tr><?php endforeach ?></tbody></table></div>
