<?php $title = 'Search'; $total = array_sum(array_map('count', $res)); ?>
<div class="pagehead"><div><h1>Search</h1><p><?= $q === '' ? 'Search posts, people, projects, services and courses.' : ($total ? "$total results for “" . e($q) . '”' : 'Nothing found for “' . e($q) . '”') ?></p></div></div>
<?php if ($q !== '' && !$total): ?><div class="card empty"><img src="<?= e(asset('img/empty.svg')) ?>" alt=""><h3>No results</h3><p>Try a different word, or ask the AI assistant where to find it.</p></div><?php endif ?>
<div class="stack gap-l">
<?php if ($res['people']): ?><section><h3>People</h3><div class="cards"><?php foreach ($res['people'] as $p): ?><a class="card person" href="<?= e(url('profile/' . $p['id'])) ?>" style="color:var(--ink)"><?= avatar($p, 46) ?><div class="grow"><b><?= e($p['full_name']) ?></b><?= verified_badge($p) ?><div class="xs muted"><?= e($p['headline'] ?: 'Student') ?></div></div></a><?php endforeach ?></div></section><?php endif ?>
<?php if ($res['posts']): ?><section><h3>Posts</h3><div class="feed" style="max-width:780px"><?php foreach ($res['posts'] as $p) partial('post_card', ['p' => $p, 'u' => $u]) ?></div></section><?php endif ?>
<?php if ($res['projects']): ?><section><h3>Projects</h3><div class="cards"><?php foreach ($res['projects'] as $p): ?><a class="card" href="<?= e(url('projects/' . $p['id'])) ?>" style="color:var(--ink)"><b><?= e($p['title']) ?></b> <span class="status-pill st-<?= e($p['status']) ?>"><?= e(str_replace('_', ' ', $p['status'])) ?></span><p class="small muted" style="margin:6px 0 0"><?= e(excerpt($p['description'], 110)) ?></p></a><?php endforeach ?></div></section><?php endif ?>
<?php if ($res['services']): ?><section><h3>Services</h3><div class="cards"><?php foreach ($res['services'] as $s): ?><a class="card" href="<?= e(url('marketplace/' . $s['id'])) ?>" style="color:var(--ink)"><b><?= e($s['title']) ?></b><div class="price" style="margin-top:6px"><?= $s['price'] ? 'AED ' . (int) $s['price'] : 'Free' ?></div></a><?php endforeach ?></div></section><?php endif ?>
<?php if ($res['courses']): ?><section><h3>Courses</h3><div class="cards"><?php foreach ($res['courses'] as $c): ?><a class="card" href="<?= e(url('learn/' . $c['id'])) ?>" style="color:var(--ink)"><b><?= e($c['title']) ?></b><div class="xs muted" style="margin-top:4px"><?= e(COURSE_CATEGORIES[$c['category']] ?? $c['category']) ?> · <?= e(ucfirst($c['level'])) ?></div></a><?php endforeach ?></div></section><?php endif ?>
</div>
